package app.crescentcash.src.utils

object Constants {
    val WALLET_NAME = "users_wallet"
    var IS_PRODUCTION = true
    var CASH_ACCOUNT_GENESIS_MODIFIED = 563620
    var MAX_OP_RETURN = 223
    var REQUEST_CODE_GET_CONTACT = 2230
    var REQUEST_CODE_SCAN_PAY_SLP_TO = 2235
    var REQUEST_CODE_SCAN_PAY_TO = 2240
    var REQUEST_CODE_SWEEP_SCAN = 2245
    var REQUEST_CODE_IMPORT_SCAN = 2250
    var REQUEST_CODE_SIG_VERIFY_MESSAGE_SCAN = 2255
    var REQUEST_CODE_SIG_VERIFY_ADDRESS_SCAN = 2260
    var REQUEST_CODE_SIG_VERIFY_SIGNATURE_SCAN = 2265
    var REQUEST_CODE_ENCRYPT_WALLET = 2270
    var REQUEST_CODE_PROMPT_PASS_STREET = 2275
    var REQUEST_CODE_PROMPT_PASS_DECRYPT = 2280
    var REQUEST_CODE_DECRYPT = 2285
    var REQUEST_CODE_GET_SLP_CONTACT = 2290
    var QR_SCAN_RESULT = "SCAN_RESULT"
    var DONATION_ADDRESS = "PM8TJLAWsHQeTmCzXmUQDsW7ZvBY5v16xMgVHCVq68jyY6miSVhzhYXMwC2fcDz8MY8UQxyAfFzJsGuATyfXkbVAnUu2EYuxfAjLTfk1QBCq9rF7Bz1o"
    var INTENT_CASH_ACCOUNT_DATA = "cashAccount"
    var INTENT_TOKEN_TICKER_DATA = "tokenTicker"
    var INTENT_TRANSACTION_POSITION_DATA = "transactionPos"
    var INTENT_PASS_PROMPT_TYPE = "promptType"
    var INTENT_SLP_PCT_DATA = "slpSyncPercent"
    var ENCRYPTED_RESULT = "ENCRYPT_RESULT"
    var DECRYPTED_RESULT = "DECRYPT_RESULT"
    var CONFIRM_PASS_RESULT = "CONFIRM_PASS_RESULT"
    var ACTION_CLEAR_SEND = "SendActivity.CLEAR_SEND"
    var ACTION_CLEAR_SLP_SEND = "SendActivity.ACTION_CLEAR_SLP_SEND"
    var ACTION_UPDATE_HOME_SCREEN_BALANCE = "MainActivity.UPDATE_HOME_SCREEN_BALANCE"
    var ACTION_UPDATE_HOME_SCREEN_THEME = "MainActivity.UPDATE_HOME_SCREEN_THEME"
    var ACTION_UPDATE_CASH_ACCOUNT_LABEL = "ReceiveActivity.ACTION_UPDATE_CASH_ACCOUNT_LABEL"
    var ACTION_CLEAR_SWEEP_TEXT = "AdvancedSettingsActivity.CLEAR_SWEEP_TEXT"
    var ACTION_UPDATE_SLP_SCREEN = "ReceiveActivity.ACTION_UPDATE_SLP_SCREEN"
}
